### ISSUE TITLE
Badge for Maven is broken

### ISSUE THREAD

**Issue by droidchef** [twitter/Serial#17]
Badge for Maven, in Readme file seems to be broken. 
![screen shot 2017-11-09 at 5 55 41 pm](https://user-images.githubusercontent.com/3158880/32618191-4c762c36-c577-11e7-9af4-612d1b2b16fb.png)

**Comment by amandeepg** [comment]
I've noticed this too, but I'm not sure why it would do that! We'll see if this happens when we upgrade the version, it might be something weird with how Github fetched the image url from shields.io

**Comment by amandeepg** [comment]
Looks like the badge always appears now, not sure what was wrong before, thanks for reporting!
