### ISSUE TITLE
Source code not distributed with library artifacts

### ISSUE THREAD

**Issue by damien5314** [twitter/Serial#21]
Hi 😄 When I import the Serial dependency with gradle, I'm not getting source code included. IDEA shows decompiled bytecode when browsing a class. 

Can you add this? Helps when debugging, also when the IDE generates code it's nice to have the real parameter names populated instead of `p0` `p1` `p2` etc.

Thanks!

**Comment by amandeepg** [comment]
Hey @damien5314, I tried to reproduce your issue, but couldn't. Can you share a screenshot of the library setup inside Android Studio/IntelliJ? It should look something like this 
<img width="633" alt="upload" src="https://user-images.githubusercontent.com/984237/32872858-eb77db7a-ca56-11e7-98f5-781288caef4a.png">

**Comment by damien5314** [comment]
@amandeepg Can you tell me how to access that window? I couldn't find "Configure Library" but I found "Library Properties" which shows me Sources+Javadoc for other libraries, but not Serial.

![screenshot 2017-11-16 09 36 41](https://user-images.githubusercontent.com/1700953/32907687-c1fdeeba-cab5-11e7-943b-36441681f86d.png)
![screenshot 2017-11-16 09 36 59](https://user-images.githubusercontent.com/1700953/32907694-c618fbac-cab5-11e7-8c94-45221fdb187c.png)

I thought it might be that I was using `jcenter()` instead of `mavenCentral()` in my build.gradle, but after adding `mavenCentral()` as my first repository and invalidating caches, it doesn't seem to change anything.

```
repositories {
    mavenCentral()
    jcenter()
    ...
}

dependencies {
    ...
    implementation("com.twitter.serial:serial:$SERIAL_VERSION") {
        exclude group: 'io.reactivex', module: 'rxjava'
    }
    ...
}
```

**Comment by damien5314** [comment]
Hmm, coming back to this again, I managed to find sources in my local gradle directory and point the IDE to the right place. So I think there must have been some Android Studio bug causing sources to not be automatically linked. Sorry for the trouble!
