### ISSUE TITLE
Translate a Chinese README ?

### ISSUE THREAD

**Issue by ParfoisMeng** [twitter/Serial#26]

**Comment by jingwei423** [comment]
hey @ParfoisMeng thanks for the suggestion.

How about sending a PR of translated Chinese README and I can work with you to get it reviewed/merged?

**Comment by ParfoisMeng** [comment]
@jingwei423 My English is poor。Are you Chinese？Can you speak Chinese？😂---by Youdao Dictionary

**Comment by amandeepg** [comment]
Fixed in https://github.com/twitter/Serial/pull/35. Thanks!
