### ISSUE TITLE
README-CHINESE.rst疑问

### ISSUE THREAD

**Issue by helianthuslulu** [twitter/Serial#39]
Hi, @jingwei423  
 if there is a clerical error in the translated doc? I'm not sure.

https://github.com/twitter/Serial/blob/master/README-CHINESE.rst/#id7 
这个文档中的

> 序列化工具方法
![image](https://user-images.githubusercontent.com/4606832/57746472-ead5d400-7703-11e9-87ef-60c8036dbf3f.png)
是不是应该修改为ClassB和ClassC？

**Comment by jingwei423** [comment]
Hi @helianthuslulu,

Nice catch, and thank you for the descriptive comment! 

That's a typo in both English and Chinese doc. We'll fix them soon!

**Comment by jingwei423** [comment]
Hey @helianthuslulu -- the typos are fixed. Check it out!
